### ISSUE TITLE
Delete key on Mac causes NERVE to crash/close browser window

### ISSUE THREAD

**Issue by SusanBrown** [Thaerious/NERVE#46]

**Comment by cutic** [comment]
Tested this today on Mac, both in Chrome and Firefox, and this did not happen. I tested a few times and it seemed to be working fine (when I press delete it only deletes the term i highlighted, kind of like un-tag).

**Comment by ilovan** [comment]
Can you both specify what document you were using for testing, as per Ed's
instructions ( it may be the document/schema that's at fault if the browser
and/or operating system are not.



On Mon, May 2, 2016 at 3:33 PM, cutic <notifications@github.com> wrote:

> Tested this today on Mac, both in Chrome and Firefox, and this did not
> happen. I tested a few times and it seemed to be working fine (when I press
> delete it only deletes the term i highlighted, kind of like un-tag).
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Thaerious/NERVE/issues/46#issuecomment-216371238>
>



-- 
Mihaela Ilovan

Project Manager
Canadian Writing Research Collaboratory
University of Alberta
4-20 Humanities Centre
Edmonton, AB
Canada T6G 2E5

780-492-7803
ilovan@ualberta.ca

**Comment by cutic** [comment]
I used Cultural Mapping - Mapping tags and tagging maps (in both Firefox and Chrome)

**Comment by Thaerious** [comment]
On the mac the delete key is backspace key and the backspace key by default (on most browsers) takes you to your last page.  Ctrl-U has been mapped to untag.  Delete will still work on PCs.  This ticket will remain open until I can find a solution to the delete key issue.

**Comment by Thaerious** [comment]
I have made this a low priority bug, as ctrl-u should work for now.

**Comment by Thaerious** [comment]
In the next major update the backspace key should now behave like the delete.  And the delete on the mac like the delete on the pc.  Hence both will untag the currently entity.  Milestone set to Allpha.2 to indicate it is fixed, but requires low priority testing.

**Comment by SusanBrown** [comment]
Does this indicate that it's ready to be tested, Ed.? I'm testing 1.5 alpha and it's still crashing but are you saying an update is imminent?

**Comment by SusanBrown** [comment]
I've added back the high priority because of the seriousness of losing your work by backspacing/deleting inadvertently.

**Comment by Thaerious** [comment]
This is now hopefully disabled, I used a jquery fix I found on stackoverflow.  The issue was disabling the backspace key prevented it from working in text boxes.  This fix checks for that.  But it still doesn't hurt to save your work often.

**Comment by SusanBrown** [comment]
Speaking of that, how about a save button that isn’t hidden in the file menu. Enhancement of course.
Sorry for not putting in separate issue ticket—about to board plane.

**Comment by cutic** [comment]
Delete and Backspace don’t do anything on Mac (they do not untag lemmas).

**Comment by cutic** [comment]
They don't do anything on PC either. You cannot untag tagged lemmas.

**Comment by Thaerious** [comment]
Delete key is currently disabled, though you can still untag with the right-click menu, or the edit menu.  This will be re-enabled soon.
